/* Write your PL/SQL query statement below */
SELECT TO_CHAR(TRANS_DATE, 'YYYY-MM') AS MONTH, 
COUNTRY, COUNT(*) AS TRANS_COUNT, 
SUM(CASE WHEN STATE='approved' THEN 1 ELSE 0 END) AS APPROVED_COUNT, 
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT, 
SUM(CASE WHEN STATE='approved' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT FROM TRANSACTIONS GROUP BY TO_CHAR(TRANS_DATE, 'YYYY-MM'), COUNTRY;